FROM maven:3-eclipse-temurin-8-alpine

WORKDIR /usr/src/optimizer

COPY entry-point.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entry-point.sh

COPY ./src ./src

COPY pom.xml ./
RUN mvn package

RUN mkdir -p imgs/in imgs/out \
    && chmod 755 imgs/in imgs/out

ENTRYPOINT [ "entry-point.sh" ]