elasticsearch:
  enabled: true
  global:
    storageClass: "gp2"
  fullnameOverride: elasticsearch

  master:
    replicaCount: 1
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
  data:
    replicaCount: 1
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
  coordinating:
    replicaCount: 1
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
  ingest:
    replicaCount: 1
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
        
  metrics:
    enabled: false
    annotations:
      helm.sh/hook: "post-install,post-upgrade"
      helm.sh/hook-weight: "5"
    service:
      type: ClusterIP
      port: 9114
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9114"
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 30s
      honorLabels: true

kibana:
  enabled: true
  global:
    storageClass: "gp2" 
  fullnameOverride: kibana
  persistence:
    storageClass: "gp2"
  ingress:
    enabled: true
    pathType: Prefix
    hostname: kibana.crabdance.com
    path: /
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  elasticsearch:
    hosts:
      - "elasticsearch.{{ .Release.Namespace }}.svc.cluster.local"
    port: "9200"
  metrics:
    enabled: false
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "_prometheus/metrics"
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 30s
      honorLabels: true
      
fluentd:
  enabled: true
  fullnameOverride: fluentd
  global:
    storageClass: "gp2"
  aggregator:
    configMap: output
    extraEnvVars:
      - name: ELASTICSEARCH_HOST
        value: "elasticsearch.default.svc.cluster.local"
      - name: ELASTICSEARCH_PORT
        value: "9200"
  forwarder:
    configMap: parser
    resources:
      requests:
        cpu: "0.25"
        memory: "256Mi"
      limits:
        cpu: "0.5"
        memory: "512Mi"
  metrics:
    enabled: false
    service:
      type: ClusterIP
      port: 24231
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 30s
      honorLabels: true