---
- name: configure httpd
  hosts: web_nodes
  become: yes
  tasks:
    - name: update repo
      apt:
        update_cache: yes
    - name: Install httpd server
      apt:
        name: apache2
        state: present
    - name: Set index.html
      get_url:
        url: https://raw.githubusercontent.com/MathoAvito/Ansible-Exercise/main/Ansible/Webfile/index.html
        dest: /var/www/html/index.html
        mode: 0755
    - name: Start httpd service
      service:
        name: apache2
        state: started
