---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cineindex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: ssh://git@cicdlab.mooo.com:8022/crommie/cineindex-argocd.git
    targetRevision: HEAD
    path: charts/cineindex
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cineindex

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true