---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: ssh://git@cicdlab.mooo.com:8022/crommie/cineindex-argocd.git
    targetRevision: HEAD
    path: charts/nginx-ingress-controller
    helm:
      valueFiles:
        - ingress-values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-controller

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true