---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: ssh://git@cicdlab.mooo.com:8022/crommie/cineindex-argocd.git
    targetRevision: HEAD
    path: charts/kube-prometheus-stack
    helm:
      valueFiles:
        - monitoring-values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      
    automated:
      selfHeal: true
      prune: true