FROM node:19-alpine3.16

WORKDIR /usr/src/cowsay

COPY ./src/package*.json ./

RUN --mount=type=cache,target=/usr/src/cowsay/.npm \
    npm set cache /usr/src/cowsay/.npm && \
    npm install

COPY ./src ./

COPY entry-point.sh /usr/local/bin
RUN chmod +x /usr/local/bin/entry-point.sh

USER node

ENTRYPOINT [ "entry-point.sh" ]
