FROM alpine:3.11 as builder

WORKDIR /app

RUN apk update && \
    apk add --no-cache python2 curl && \
    curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py && \
    python2 get-pip.py && \
    pip install virtualenv && \
    virtualenv /app/venv


ENV VIRTUAL_ENV=/app/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./project/flask-app/requirements.txt ./project/flask-app/app.py ./

RUN pip install -r requirements.txt

FROM alpine:3.11 as runner

WORKDIR /usr/src/foodtrucks

RUN apk update && \
    apk add --no-cache python2 

COPY --from=builder /app/venv venv
COPY --from=builder /app/app.py ./

ENV VIRTUAL_ENV=/usr/src/foodtrucks/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

EXPOSE 5000

ENTRYPOINT [ "python", "app.py"]