FROM python:3.9-slim as builder

WORKDIR /app

RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential python3-dev libpq-dev && \
    pip install --upgrade pip && \
    python3 -m venv venv

ENV VIRTUAL_ENV=/app/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./project .

RUN pip install -r requirements.txt

FROM python:3.9-slim as runner

WORKDIR /usr/src/gutendex

RUN apt-get update && apt-get install --no-install-recommends -y \
    rsync python3-dev libpq-dev build-essential && \
    pip install --upgrade pip

COPY --from=builder /app/venv venv
COPY --from=builder /app/manage.py .
COPY --from=builder /app/gutendex/ ./gutendex
COPY --from=builder /app/catalog_files/ ./catalog_files
COPY --from=builder /app/books/ ./books
COPY db_healthchecker.py .
COPY entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

ENV VIRTUAL_ENV=/usr/src/gutendex/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

ENTRYPOINT [ "entrypoint.sh" ]