---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  {{ if not .Values.ingress.enabled }}
  {{ .Values.service.type eq .Values.appAltServive.type}}
  type: {{ .Values.service.type }}
  {{ end }} 
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 80