---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080