version: '3.9'
services:

  lavagna-db:
    image: mysql:5.7
    restart: always
    container_name: lavagnaDB
    hostname: lavagna-db
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend.net
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "lavagna-db",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 20s
      retries: 5
    volumes:
      - data-db:/var/lib/mysql

  lavagna:
    image: lavagna
    build: .
    restart: always
    container_name: lavagna
    environment:
      DB_PASS: ${MYSQL_PASSWORD}
      DB_URL: ${DB_URL}
      DB_DIALECT: ${DB_DIALECT}
      DB_USER: ${MYSQL_USER}
      DB_HOST: ${DB_HOST}
      SPRING_PROFILE: ${SPRING_PROFILE}
    expose:
      - 8080
    networks:
      - backend.net
      - frontend.net
    depends_on:
      lavagna-db:
        condition: service_healthy

  proxy:
    image: lavagna-proxy
    build:
      dockerfile: dockerfile.nginx
    restart: always
    container_name: lavagna-proxy
    expose:
      - 80
    networks:
      - frontend.net
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - lavagna

networks:
  backend.net:
  frontend.net:
volumes:
  data-db:
