FROM maven:3.6.3-openjdk-8 as builder

WORKDIR /usr/src/lavagna

COPY project/ .

RUN mvn verify

FROM openjdk:8-jre-alpine as runner

WORKDIR /usr/src/lavagna

EXPOSE 8080

RUN apk update && \
    apk add --no-cache mysql-client

COPY entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

COPY --from=builder /usr/src/lavagna/target/lavagna-jetty-console.war .

ENV DB_DIALECT ""
ENV DB_URL ""
ENV DB_USER ""
ENV DB_PASS ""
ENV DB_HOST ""
ENV SPRING_PROFILE ""

ENTRYPOINT [ "entrypoint.sh" ]