fullnameOverride: monitoring

alertmanager:
  ingress:
    enabled: true
    annotations: #{}
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"

    hosts: 
      - alertmanager.mooo.com
    paths:
      - /
    pathType: Prefix

    tls: []
    # - secretName: alertmanager-general-tls
    #   hosts:
    #   - alertmanager.example.com

grafana:
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts: 
      - grafana.jumpingcrab.com
    path: /

    tls: []
    # - secretName: grafana-general-tls
    #   hosts:

prometheus:
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
      - prome-theus.mooo.com
    paths:
      - /
    pathType: Prefix
    tls:
      []
      # - secretName: prometheus-general-tls
      #   hosts:
      #     - prometheus.example.com

  prometheusSpec:
    additionalScrapeConfigs: #[]
      - job_name: ingress_controller
        honor_timestamps: true
        scrape_interval: 1m
        scrape_timeout: 1m
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - ingress-controller-metrics.ingress-controller.svc.cluster.local:9913

      - job_name: cert-manager
        honor_timestamps: true
        scrape_interval: 1m
        scrape_timeout: 1m
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - cert-manager-controller-metrics.cert-manager.svc.cluster.local:9402

      - job_name: mongodb
        honor_timestamps: true
        scrape_interval: 1m
        scrape_timeout: 1m
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - mongodb-metrics.cineindex.svc.cluster.local:9216

      - job_name: cineindex
        honor_timestamps: true
        scrape_interval: 1m
        scrape_timeout: 1m
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - cineindex.cineindex.svc.cluster.local:8080

      - job_name: fluentd
        honor_timestamps: true
        scrape_interval: 1m
        scrape_timeout: 1m
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - fluentd-metrics.logging.svc.cluster.local:24231