apiVersion: v2
name: cineindex
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
icon: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

dependencies:
- name: mongodb
  version: x.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled